### PR TITLE
Add missing socials & Make footer sticky

### PR DESCRIPTION
**Pull request by daynamariejpembie**
I accidentally added instagram as one of the socials. I have since removed it to show the below with all the socials necessary:

socials1-pr

I have also made the footer sticky to the bottom of the page: 
sticky-footer

Any feedback on my work would be appreciated :) !

### CODE REVIEW

**Comment by zarela** [comment]
@daynamariejpembie could you solve the merge conflicts please? :)

**Comment by daynamariejpembie** [comment]
@zarela done :)

**Comment by zarela** [comment]
Hi! So sorry I think I completely used the wrong word here. Actually wanted the footer to be at the end but not sticky. I know I used the word. I apologize for te confusion.
So for example, I wanted to fix this issue:
Screenshot 2024-10-23 at 12 44 17 AM

I am not sure exactly what is called, so that stays at the end but not sticky. The first page is fine because we have a lot of content, so the problem is not there, but the second page, which you can just add `/events` to the end of the url and you will see.

**Review by jonathans199 — COMMENTED** [review]
@daynamariejpembie 
We should be able to accomplish these styles now via Tailwind only, without the need of an extra css module file.

Like this for example: 

```
// layout.jsx
const Layout = ({ children }) => (
  <div className="flex flex-col min-h-screen">
    <Header />
    <main className="flex-grow">
      {children}
    </main>
    <Footer className="sticky bottom-0 w-full bg-gray-100" />
  </div>
);
```

**Review by zarela — APPROVED** [review]

**Review by zarela — APPROVED** [review]

**Comment by zarela** [comment]
Closes #38

**Pull request merged**
