### PR TITLE
Footer with logos and links

### PR DESCRIPTION
**Pull request by Madelene**
Heya @zarela . Here's another PR for you, whenever you have a moment!

Let me know if you prefer different-looking logos. Here's what the footer looks like:
Screen Shot 2022-10-14 at 16 47 22

### CODE REVIEW

**Comment by Madelene** [comment]
This PR is from [this issue](https://github.com/swfl-coders/tech-alliance-website/issues/6)

**Comment by zarela** [comment]
@Madelene, so sorry I haven't updated the issue and I wasn't super specific. 
We also have LinkedIn and Twitter. I can add those later, but is it possible to just use the circle logos so when we add all the others they are consistent?

Let's use these type of logos please:
Screen Shot 2022-10-15 at 10 29 06 AM

**Comment by zarela** [comment]
@Madelene one more change, so sorry I haven't updated the issue and I wasn't super specific. 
We also have LinkedIn and Twitter. I can add those later, but is it possible to just use the circle logos so when we add all the others they are consistent?

Let's use these type of logos please:
Screen Shot 2022-10-15 at 10 29 06 AM

**Comment by Madelene** [comment]
@zarela How about these?

Screen Shot 2022-10-15 at 14 48 56

**Pull request merged**
