### PR TITLE
added logos to the site and made it responsive

### PR DESCRIPTION
**Pull request by rashad3412**

### CODE REVIEW

**Comment by rashad3412** [comment]
added logos, to the page and Made the web page responsive using css.

**Comment by zarela** [comment]
@rashad3412 please read my note on the issue. We are not accepting PRs unless:
1. You asked on the issues as the first person
2. You are assigned to the issue
3. You are a member of our community.

If you are a member of our community, I apologize, but I need you to please identify yourself.
Thank you in advance

**Comment by rashad3412** [comment]
Hey I am not a member of the community, how do I become a member? I found it through research I am trying to contribute to my first repo and this is my first time so I really need help on how everything works. Sorry for any confusion I may have caused and thank you for your quick response and feedback.

**Comment by zarela** [comment]
@rashad3412 I will close this PR because you are working on something that was assigned to another person.
Our community is based of Florida and to be a member you have to attend to our events. Lastly, this PR is not valid as the logos are not round. 

We thank you for your interest but at this time we are not receiving new contributors as we have reserved these tickets for our community only, at least during October because is Hacktoberfest.

**Pull request closed without merging**
