### PR TITLE
  updated navigation to have bottom blue bar and removed unused modul…

### PR DESCRIPTION
**Pull request by jonathans199**
…e.css file for header

Screenshot 2024-10-23 at 11 48 36 AM

### CODE REVIEW

**Comment by zarela** [comment]
@jonathans199 is it possible to make it the same thickness of what we previously had? or maybe not as much but at least double of what it is right now. Also we had a drop shadow there and we not longer have it. I will prefer we use the same thickness since the cards have the same thickness when you hover over


Here is the original

https://www.techallianceswfl.org/

**Review by zarela — CHANGES_REQUESTED** [review]
@jonathans199 is it possible to make it the same thickness of what we previously had? or maybe not as much but at least double of what it is right now. Also we had a drop shadow there and we not longer have it. I will prefer we use the same thickness since the cards have the same thickness when you hover over

Here is the original

https://www.techallianceswfl.org/

**Comment by jonathans199** [comment]
@zarela  made the following updates: 
1. Made the logo larger
2. increased the blue bar to exact size as current site
3. Increased shadow

Screenshot 2024-10-29 at 3 40 00 PM

**Comment by jonathans199** [comment]
Branch was updated with changes in staging, please advise

Screenshot 2024-11-01 at 7 19 48 PM

**Review by zarela — APPROVED** [review]
Looks beautiful! Thank you! 🎉

**Comment by zarela** [comment]
Closes #33

**Pull request merged**
