### PR TITLE
Feature/navigation implementation

### PR DESCRIPTION
**Pull request by jonathans199**
Screenshot 2024-09-17 at 5 16 45 PM

### CODE REVIEW

**Comment by allantito** [comment]
@zarela @ethanlanders

**Comment by jonathans199** [comment]
@zarela same conflicts here, when you have a chance, thank you.

**Comment by zarela** [comment]
@jonathans199 this is the same comment. This is happening because you need the most recent copy from main. You can delete the package-lock file and I can do an npm install in the main branch.

Also, I can't approve this PR because is making big changes to the desire look we have on the mockups, so if you can remove the items we don't need I can approve them. TY

**Comment by jonathans199** [comment]
Closing for new PR wip

**Pull request closed without merging**
